#+title: Backlog
#+options: date:nil toc:nil author:nil num:nil
#+tags: story(s) epic(e) task(t) note(n) spike(p)

* Backlog

This file contains all stories that haven't been assigned to a sprint.

** Development Stories

Stories that we intend to look at, at some point.

*** Experiment with the new application backgrounds

We have created new bases for the application icons, try making a
dogen icon with the burgundy base to see if its better than the old
one.

*** Create an icon for Creris

This is the credit risk application. Suggestion document with AAA.

MC: App icon is cool, but can we make the AAA on the middle of the
document and also make it look gray like the dogen cog? the AAA is the
same metaphor as the cog basically so it should try to look the same
style

*** Missing currency pairs

**** EURCHF eu-ch
**** EURRMB eu-cn
**** EURJPY eu-jp
**** EURGBP eu-gb
**** GBPNOK gb-no
**** GBPSEK gb-se
**** GBPISK gb-is
**** GBPCHF gb-ch
**** GBPIND gb-in
**** GBPJPY gb-jp
**** CHFJPY ch-jp
*** More emerging countries
**** AR
**** KO
** Won't fix

Stories which we do not think we are going to work on.
